### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by ssebastianoo** [Naila/Discord-chat-replica#21]
Hello, I don't get how does that time value represents a date and how can I convert a date in a number like that.

**Comment by Kanin** [comment]
Assuming from your repos you're using python?

**Comment by ssebastianoo** [comment]
yep

**Comment by ssebastianoo** [comment]
I making a bot that auto bumps in the .json datas and I have to retrive thay value

**Comment by Kanin** [comment]
```python
message_dict = {
    "author": str(message.author.id),
    "id": str(message.id),
    "type": message.type.value,
    "time": int(message.created_at.timestamp() * 1000)
}
```
Is what I use for each messages payload

**Comment by Kanin** [comment]
https://github.com/Naila/Naila.py/blob/17acd15c66a20f3f9b7b9a390356f8570b401b88/utils/functions/archive.py#L100-L105 you can see a (very poor) example here

**Comment by ssebastianoo** [comment]
thanks!
